apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  # Gitリポジトリ情報
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook

  # デプロイ先
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # 同期ポリシー（手動同期）
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

  # プロジェクト
  project: default
